"""
    Configuration file for package.
    Stores names of directories and files.
"""

import datetime

# ------ EDIT BELOW IF REQ -------------------------------------------------------------- #

# DIRECTORIES
GLOBAL_OUTPUT_DIRECTORY = 'data_files/output_files/'
GLOBAL_INPUT_DIRECTORY = 'data_files/input_files/'
GLOBAL_AUTOGENERATED_DIRECTORY = 'data_files/auto_generated/'
HISTORY_DIR = 'history/'

# UNIQUE FILE ID GENERATION
UNIQUE_FILE_ID = datetime.datetime.now().strftime("%Y-%m-%d-%H-%M-%S") # always same for 1 run

# INPUT FILE NAMES
CURRENT_INPUT_FILE = '' # gets updated in pybullet_program.py
INPUT_ARBITRARY_FILE_NAME = 'input_arbitrary.csv'
INPUT_SINE_FILE_NAME = 'input_sine.csv'
INPUT_STEP_FILE_NAME = 'input_step.csv'
INPUT_CIRCULAR_FILE_NAME = 'input_circ.csv'

# TRAJ FILE NAMES

TRAJ_PLATFORM_FILE_NAME = 'traj_platform.csv' # xyzrpy
TRAJ_JOINTS_FILE_NAME = 'traj_joints.csv' # joint angles

# TRAJ_PLATFORM_FILE_NAME = 'traj_platform_solo.csv' # xyzrpy
# TRAJ_JOINTS_FILE_NAME = 'traj_joints_solo.csv' # joint angles

# TRAJ_PLATFORM_FILE_NAME = 'traj_platform_pybullet.csv' # xyzrpy
# TRAJ_JOINTS_FILE_NAME = 'traj_joints_pybullet.csv' # joint angles

# FINAL OUTPUT FILES
PYBULLET_DATA_OUTPUT_FILE_NAME = 'pybu_data.csv'
SOLO_DATA_OUTPUT_FILE_NAME = 'solo_data.csv'

PYBULLET_CALCULATED_FILE_NAME = 'pybu_calculated.csv'
SOLO_CALCULATED_FILE_NAME = 'solo_calculated.csv'

# CALIBRATION FILES
GLOBAL_CALIBRATION_FILES_DIRECTORY = 'data_files/calibration_files/'
CALIBRATION_PHASE_1_FILE = 'solo_phase1_calibrated_offsets.csv'
CALIBRATION_PHASE_2_FILE = 'solo_phase2_calibrated_offsets.csv'

# TIME FOR INTERPOLATINS IN SOLO CONTROL 
TIME_INTERPOLATE_HOME = 1000 # ms
TIME_INTERPOLATE_LANDING = 2000 # ms

# THRESHOLDS FOR TRAJECTORY GENERATION
THRESHOLD_FREQUENCY = 5 # Hz
THRESHOLD_AMPLITUDE = 35 # mm/deg

# --------------------------------------------------------------------------------------- #


# ------ DO NOT EDIT BELOW -------------------------------------------------------------- #
def generate_unique_name(name=''):
    return str(name)[:-4] + '-' + UNIQUE_FILE_ID + '.csv'

TRAJ_PLATFORM_FILE_UNIQUE = generate_unique_name(TRAJ_PLATFORM_FILE_NAME)
TRAJ_JOINTS_FILE_UNIQUE = generate_unique_name(TRAJ_JOINTS_FILE_NAME)

PYBULLET_DATA_OUTPUT_FILE_UNIQUE = generate_unique_name(PYBULLET_DATA_OUTPUT_FILE_NAME)
SOLO_DATA_OUTPUT_FILE_UNIQUE = generate_unique_name(SOLO_DATA_OUTPUT_FILE_NAME)
PYBULLET_CALCULATED_FILE_UNIQUE = generate_unique_name(PYBULLET_CALCULATED_FILE_NAME)
SOLO_CALCULATED_FILE_UNIQUE = generate_unique_name(SOLO_CALCULATED_FILE_NAME)
# --------------------------------------------------------------------------------------- #